### ISSUE TITLE
请问训练需要的数据集：data/VimeoTecoGAN/GT.lmdb 怎么得到

### ISSUE THREAD

**Issue by riverlight** [Thmen/EGVSR#2]
似乎没有制作 lmdb 的脚本？

**Comment by riverlight** [comment]
找到了，./scripts/create_lmdb.py，谢谢，close了

**Comment by cloudlakecho** [comment]
@riverlight Thanks for sharing information. I actually tried to run the "create_lmdb.py" with downloaded "VimeoTecoGAN" with this parameter: 
`$ python scripts/create_lmdb.py --dataset VimeoTecoGAN --data_type GT`  
I am facing error of missing the "GT" folder. I don't see the "GT" nor "Bicubic4xLR" folder in the downloaded "VimeoTecoGAN" folder. What value I have to choose for the "data_type" parameter?
