### ISSUE TITLE
how to run the test program

### ISSUE THREAD

**Issue by daizzhisheng** [Thmen/EGVSR#4]
I put some images into dir /data/Vid4/GT for test,  but I don't know  what's the mean of "data/Vid4/Gaussian4xLR",   

python codes/main.py --exp_dir test --mode test --model EGVSR --opt /opt/EGVSR-master/experiments_BD/EGVSR/001/test.yml

2021-07-22 11:01:23,123 [INFO]: ========================================
2021-07-22 11:01:23,123 [INFO]: Testing model: EGVSR_iter420000
2021-07-22 11:01:23,123 [INFO]: ========================================
2021-07-22 11:01:24,793 [INFO]: Testing on test1: Vid4
Traceback (most recent call last):
  File "codes/main.py", line 341, in <module>
    test(opt)
  File "codes/main.py", line 182, in test
    test_loader = create_dataloader(opt, dataset_idx=dataset_idx)
  File "/opt/daizhsh/EGVSR-master/codes/data/__init__.py", line 58, in create_dataloader
    dataset = PairedFolderDataset(data_opt, scale=opt['scale'])
  File "/opt/daizhsh/EGVSR-master/codes/data/paired_folder_dataset.py", line 21, in __init__
    lr_keys = sorted(os.listdir(self.lr_seq_dir))
FileNotFoundError: [Errno 2] No such file or directory: 'data/Vid4/Gaussian4xLR'

Thank you for you reply!

**Comment by Thmen** [comment]
Vid4 is the test dataset with a pair of ground true (GT) image samples and low resolution (LR) input ones.
If you want to test the VSR model, you could refer to the ''test.sh'' script. Hope it works for you!

**Comment by Thmen** [comment]
Vid4 is the test dataset with a pair of ground true (GT) image samples and low resolution (LR) input ones.
If you want to test the VSR model, you could refer to the ''test.sh'' script. Hope it works for you!

**Comment by cloudlakecho** [comment]
@Thmen thanks for the information, but the "test.sh" doesn't work correctly with current situation.  

The weblink to Vid4 dataset is broken (in the ReadMe), so I download it from another [Google Drive](https://drive.google.com/drive/folders/1An6hF1oYkeWxfOBxxKm073mvgIFrBNDA) (ref: [issue 16](https://github.com/Thmen/EGVSR/issues/160)). Unfortunately, it doesn't have the folder of the ground truth, like "Gaussian4xLR". It looks like that I have to generate the folder. How could we prepare dataset for testing?
